### ISSUE TITLE
Parsing bug

### ISSUE THREAD

**Issue by malezjaa** [cijiugechu/nodejs-semver#2]
Hi, when parsing ranges like `>=1.0.0 <2.0.0` everything works but when `minor` or `patch` is missing (>=2.2.7<3) it throws error `No valid ranges could be parsed`

**Comment by cijiugechu** [comment]
This result is expected; [semver](https://github.com/npm/node-semver) as a reference implementation, `nodejs-semver` aligns with it in this behavior: in [semver](https://github.com/npm/node-semver), a syntax like this `>=2.2.7<3` (note, no space) will throw a TypeError. If you want to achieve this syntax, you can add a space, i.e. write it as: `>=2.2.7 <3`.

**Comment by malezjaa** [comment]
Thank you! I understand it now.
